<template>
  <v-dialog v-model="dialog"  persistent max-width="600px">
    <template v-slot:activator="{ on }">
      <v-list-item link v-on="on">
        <v-list-item-action>
          <v-icon>mdi-upload</v-icon>
        </v-list-item-action>
        <v-list-item-content>
          <v-list-item-title>Upload Report</v-list-item-title>
        </v-list-item-content>
      </v-list-item>
    </template>

    <v-card>
      <v-card-title>
        <span class="headline">Upload Report File</span>
      </v-card-title>
      <v-card-text>
        <small>Use this form to upload a CSV file generated by TORQUE for one of your sessions.</small>
        <v-form ref="form" v-model="valid" @keyup.native.enter="submit">
          <v-file-input
            outlined dense
            label="CSV file"
            class="mt-4"
            v-model="file"
            :rules="rules"
          />
        </v-form>
        <div class="d-flex justify-end error--text" v-if="error">
          {{ error }}
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn color="blue darken-1" text @click="dialog = false" :disabled="loading">
          Close
        </v-btn>
        <v-btn color="blue darken-1" text @click="submit" :disabled="!valid" :loading="loading">
          Save
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>
import FORM_RULES from '@/resources/forms/rules';


export default {
  data: () => ({
    error: null,
    dialog: false,
    file: null,
    loading: false,
    rules: [
      FORM_RULES.required,
      FORM_RULES.fileSize,
      value => !value || value.type === 'text/csv' || 'Please upload a CSV file.',
    ],
    valid: false,
  }),
  methods: {
    submit() {
      this.error = null;
      this.loading = true;

      const formData = new FormData();
      formData.append('file', this.file);

      const config = { headers: { 'Content-Type': 'multipart/form-data' } };

      this.$requests.post('/obd/upload/', formData, config)
        .then(() => {
          this.dialog = false;
          window.location.reload();
        })
        .catch((error) => {
          this.error = error.response.data.message || 'Unable to process file';
        })
        .then(() => this.loading = false);
    },
  },
  watch: {
    dialog(value) {
      if (value === false) {
        this.error = null;
        this.$refs.form.reset();
      }
    },
  },
};
</script>
